---
- hosts: all
  gather_facts: no
  #vars:
  #  file: globals.yml
  #vars_files:
  #  - "{{ file }}"
  tasks:
  - name: Get Ontapi version
    na_ontap_gather_facts:
      state: info
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      gather_subset: "aggregate info"
 
